GET http://localhost:4200/books
 
###
 
GET  http://localhost:4200/books/1
 
###
 
GET http://localhost:4200/books?title=test
 
 
###
POST http://localhost:4200/books
Content-Type: application/json
 
{
    "title": "Чистий код",
    "price": 1000,
    "is_active": true
}